### ISSUE TITLE
Flux lora training Error with Batch >1 

### ISSUE THREAD

**Issue by Desm0nt** [ostris/ai-toolkit#59] opened 2024-08-14 12:14 UTC
On the current version in linux, if you set batch to more than 1, the start of Flux Lora training aborts with this error. The old version (commit https://github.com/ostris/ai-toolkit/commit/6d31c6db730a9cba3004eae1a3d7283c663d9295) does not have this problem.

![Снимок](https://github.com/user-attachments/assets/a269615a-a47b-4199-a864-c56ecf1d707a)

**Comment by WarAnakin** [comment] 2024-08-14 20:17
this is not caused by the batch size, it's caused by `linear_timesteps` being true. 
Comment it out like in my example
![image](https://github.com/user-attachments/assets/5d820620-0f5e-4a2a-86ba-2bf8b36c9962)

**Comment by jaretburkett** [comment] 2024-08-19 03:47
This should be resolved with and without `linear_timestep` now.

**Closed by jaretburkett** 2024-08-19 03:47 UTC
